name: Feature Branch

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kentaro-m/task-completed-checker-action@v0.1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
